name: DevOps Lab Exercise
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - "*"  # Tüm dallarda çalışacak şekilde ayarlandı
  pull_request:
    branches:
      - "*"  # Pull request için de tüm dalları kapsar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
